# config.py

TOKEN = '7341170491:AAGVNu7Iq0xWbQbqvjxXBOQHVi4mOo2h7Pc'

# Twitter API Keys and Tokens
TWITTER_API_KEY = 'FPwVFnfbkA37Tz8qbVtmV7lGY'
TWITTER_API_SECRET_KEY = '216O64kXZ7tb5gRRGHys6tg1hTbNtTjZHGkrYr2LftCDkPTbnf'
TWITTER_ACCESS_TOKEN = '1727012426200068096-5Nqs3Bn2rm8ZTazw9B1FcgmbaCINGGN'
TWITTER_ACCESS_TOKEN_SECRET = 'tOfFR4f7sVsecONFEeUdo6qKqKLRYRwSLQARK3AiCgIEz'
TWITTER_BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAABqUuAEAAAAA8fcNoOweODoEPlv9P1vGjB7svWE%3DWYeCqRwkWppqdX4Qe3PRgp09mTDBN964dUkT5PI99gk20jN2yI'

# Other API Keys
HIBP_API_KEY = 'YOUR_HIBP_API_KEY'
STRIPE_API_KEY = 'YOUR_STRIPE_SECRET_KEY'
COINBASE_COMMERCE_API_KEY = 'YOUR_COINBASE_COMMERCE_API_KEY'
GOOGLE_API_KEY = 'YOUR_GOOGLE_API_KEY'
CUSTOM_SEARCH_ENGINE_ID = 'YOUR_CUSTOM_SEARCH_ENGINE_ID'
